name: Hourly Weather Update

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  push:
    branches: [main]
  workflow_dispatch: # Manual trigger option

jobs:
  scrape-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run weather scraper
        run: python src/weather_scraper.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api/ data/
          if git diff --staged --quiet; then
            echo "No weather changes to commit"
          else
            git commit -m "Weather update $(date)"
            git push
          fi

      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Weather data collection failed',
              body: `Weather data collection failed on ${new Date().toISOString()}. Check logs: ${context.payload.repository.html_url}/actions/runs/${context.runId}`
            })
